export const ADD_MINION = 'ADD_MINION';
export const ADD_TAVERN_MINIONS_TO_POOL = 'ADD_TAVERN_MINIONS_TO_POOL';
export const REMOVE_TAVERN_MINIONS_FROM_POOL = 'REMOVE_TAVERN_MINIONS_FROM_POOL';
export const GET_CURRENT_ROLL = 'GET_CURRENT_ROLL';
export const GET_UNIQUE_MINIONS = 'GET_UNIQUE_MINIONS';
export const REMOVE_MINION = 'REMOVE_MINION';
export const SET_TIER = 'SET_TIER';
export const UPDATE_POOL = 'UPDATE_POOL';